spring:
  main.allow-bean-definition-overriding: true
  web.resources.mime-mappings.webmanifest: application/manifest+json
  mvc.async.request-timeout: ${SYSTEM_CONNECTIONTIMEOUTMILLISECONDS:1200000}
  thymeleaf.encoding: UTF-8
  jpa.open-in-view: false
  servlet.multipart:
    max-file-size: 2000MB
    max-request-size: 2000MB
  devtools:
    restart:
      enabled: true
      exclude: stirling.software.proprietary.security/**
    livereload.enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.nrlkjfznsavsbmweiyqu.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ${SAAS_DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      res
  
multipart.enabled: true
logging.level:
  org:
    springframework: WARN
    hibernate: WARN
    jetty: WARN
#    springframework.security.saml2: TRACE
#    springframework.security: DEBUG
#    opensaml: DEBUG
#  stirling.software.SPDF.config.security: DEBUG
  com.zaxxer.hikari: WARN
  
server:
  forward-headers-strategy: NATIVE
  error:
    path: /error
    whitelabel.enabled: false
    include-stacktrace: always
    include-exception: true
    include-message: always
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
    context-path: ${SYSTEM_ROOTURIPATH:/}

# Change the default URL path for OpenAPI JSON
springdoc:
  api-docs.path: /v1/api-docs
  swagger-ui:
    url: /v1/api-docs
    path: /index.html

posthog:
  api:
    key: ${POSTHOG_API_KEY:phc_fiR65u5j6qmXTYL56MNrLZSWqLaDW74OrZH0Insd2xq}
  host: ${POSTHOG_HOST:https://eu.i.posthog.com}

supabase:
  id: ${SUPABASE_PROJECT_ID:nrlkjfznsavsbmweiyqu}
  publishable-key: ${SUPABASE_PUBLISHABLE_KEY:rp7EBq9Dk-ZPCSe7EMWD7JZ6rMulReSUmJ4WIHowMl1AlCC6m1xA3UsBctHRbFkttik9pReYltrWzt7Ft1aap36_S2tKRzEN9qngJM1D7yd2s0Ok0kLeC54DxBvuqQVKe4dk6g_XC7ElV8w6JUQBN9xMLbnMQG49qvq2syugk-Ujj1M9VGsNr85HdgAFymODW3vI4w1hrz4rCDOU_uuDDGHoEvChnFVZ_tmO80IUKUCiWIIzkBn8k8mnmbnC0vCRMV-YT1J7DS-pznuqcEZhotJ3DnD3TwNJevVklo7QfZGL6hyIK-t5DNMBc3uujS1bZ9bLA3RMqXWgD9ZTmjcutw}
  jwks:
    url: https://nrlkjfznsavsbmweiyqu.supabase.co/auth/v1/.well-known/jwks.json

# Set up a consistent temporary directory location
java.io.tmpdir: ${stirling.tempfiles.directory:${java.io.tmpdir}/stirling-pdf}
